name: Q-ProstateNet
channels:
  - plotly
  - defaults
  - conda-forge
dependencies:
  - pip=21.3.1
  - future=0.18.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - imageio=2.8.0
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - markdown=3.1.1
  - numpy=1.18.1
  - pandas=1.0.3
  - plotly=4.12.0
  - protobuf=3.11.4
  - python=3.7.7
  - pyyaml=5.3.1
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - tensorboard=2.0.2
  - tensorflow=2.7.0
  - yaml=0.1.7
  - plotly=4.12.0
  - pip:
      - adjusttext==0.7.3.1
      - lifelines==0.26.4
      - matplotlib==3.1.3
      - psutil==5.7.0
      - networkx==2.2
      - pyvis==0.1.7.0
      - requests==2.23.0
      - rope==0.16.0
      - seaborn==0.10.0
      - toml==0.10.2
      - upsetplot==0.6.0
      - urllib3==1.24.3
      - xlrd==1.2.0
